services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack-main
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=lambda,sns,s3,dynamodb,apigateway,cloudformation,ssm,secretsmanager,iam,sts,logs
      - LOCALSTACK_DOCKER_NAME=localstack-main
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_DOCKER_NETWORK=lawpath-network
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./.localstack:/var/lib/localstack"
    networks: [lawpath]

  qdrant:
    image: qdrant/qdrant:v1.7.0
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - "./qdrant_storage:/qdrant/storage"
    networks: [lawpath]

networks:
  lawpath:
    name: lawpath-network
